graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
   
spring: 
  h2:
    console:
      enabled: true
      path: /h2-console
      
graphiql:
    mapping: /graphiql
    endpoint: /graphql
    enabled: true
    cdn:
        enabled: false
        version: 0.13.0   